-- FILE GENERATED BY JOKER FORGE
-- Mod: Queen's Sillies
-- Author(s): queen of stupid
-- Version: 1.0.0
-- Description: Various jokers made by me for my friends :3

local mod = SMODS.current_mod

mod.config = {}

-- Atlas
SMODS.Atlas({
    key = "CustomJokers", 
    path = "CustomJokers.png", 
    px = 71,
    py = 95, 
    atlas_table = "ASSET_ATLAS"
}):register()
SMODS.Atlas({
  key = "modicon",
  path = "queenicon.png",
  px = 32,
  py = 32
})
SMODS.current_mod.optional_features = function()
    return {
        quantum_enhancements = true
    }
end


jonklers = {
	"queen", -- legendary jokers
	"wisp",
	"hemlock",
	"cobalt",
	"calla",
	"lillie", -- Molly Jokers
	"constant",
	"boiwattson", -- PMD Jokers
	"bootandheel",
	"brittanyandfraisey",
	"grovyle",
	"potato", -- PMDND Jokers
	"apricot",
	"samanthany", 
	"snacky", 
	"dex",
	"nevanya",
	"wonder",
	"carl",
	"cocoa",
	"wontbereplaced",
	"spelljammingmercenaries", -- Party Jokers
	"holloandespa", -- Misc Jokers
	"etherealconnection",
	"e",
	"moose",
	"followed"
}

function loadshit(items, path)
  for i = 1, #items do
    SMODS.load_file(path .. "/" .. items[i] .. ".lua")()
  end
end

loadshit(jonklers, "stuff/jonklers")

to_big = to_big or function(num)
  return num
end
to_number = to_number or function(num)
  return num
end

local old_g_funcs_can_select_card = G.FUNCS.can_select_card
G.FUNCS.can_select_card = function(e)
  if e.config.ref_table.ability.name == "Lillie" and e.config.ref_table.ability.extra.slots >= 1 then 
    e.config.colour = G.C.GREEN
    e.config.button = 'use_card'
  else
    old_g_funcs_can_select_card(e)
  end
end

local old_g_funcs_check_for_buy_space = G.FUNCS.check_for_buy_space
G.FUNCS.check_for_buy_space = function(card)
  if card.ability.name == "Lillie" and card.ability.extra.slots >= 1 then
    return true
  end
  return old_g_funcs_check_for_buy_space(card)
end

return mod